apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliveryPacking
  labels:
    app: deliveryPacking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliveryPacking
  template:
    metadata:
      labels:
        app: deliveryPacking
    spec:
      containers:
        - name: deliveryPacking
          image: username/deliveryPacking:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5